# docker-compse.yml
# version: "3.3"

app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  environment:
    DATABASE_HOSTNAME: 'db'
    DATABASE_USERNAME: 'root'
    DATABASE_PASSWORD: ''
  volumes:
    - .:/app/webapp
  ports:
    - "3000:3000"
  links:
    - db
  tty: true
  stdin_open: true
db:
  image: mysql:5.7.18
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
redis:
  image: redis:3.2.4-alpine
  ports:
    - 46379:6379
