access_token_header: "X-Auth-Token"
access_token_value_prefix: "Bearer"
expired_date_token: 1

validations:
  email_regex: !ruby/regexp '/\A([a-zA-Z0-9][\w\.\+\-]*)@([\w.\-]+\.+[\w]{2,})\z/'
  strings:
    max_length: 255

accounts:
  reset_password_token:
    expires_in: <%= 1.hour %>
    length: 6
  name:
    max_length: 255

auth_tokens:
  token:
    max_length: 8
    secure_length: 8
  short_expires_in: <%= 1.day %>
